name: Build Windows version of RustDesk only

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      upload-tag:
        type: string
        default: "nightly"

env:
  SCITER_RUST_VERSION: "1.75"
  RUST_VERSION: "1.75"
  FLUTTER_VERSION: "3.24.5"
  VCPKG_COMMIT_ID: "6f29f12e82a8293156836ad81cc9bf5af41fe836"
  VERSION: "1.4.0"
  UPLOAD_ARTIFACT: "${{ inputs.upload-artifact }}"
  TAG_NAME: "${{ inputs.upload-tag }}"
  SIGN_BASE_URL: "${{ secrets.SIGN_BASE_URL }}"
  SIGN_SECRET_KEY: "${{ secrets.SIGN_SECRET_KEY }}"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-RustDeskTempTopMostWindow:
    uses: ./.github/workflows/third-party-RustDeskTempTopMostWindow.yml
    with:
      upload-artifact: ${{ inputs.upload-artifact }}
      target: windows-2022
      configuration: Release
      platform: x64
      target_version: Windows10
    strategy:
      fail-fast: false

  build-for-windows-flutter:
    name: Build Windows (Flutter)
    needs: [build-RustDeskTempTopMostWindow, generate-bridge]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/download-artifact@master
        with:
          name: bridge-artifact
          path: ./

      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15.0.6"

      - uses: subosito/flutter-action@v2.12.0
        with:
          channel: stable
          flutter-version: "3.24.5"

      - name: Replace engine
        run: |
          flutter doctor -v
          flutter precache --windows
          Invoke-WebRequest -Uri https://github.com/rustdesk/engine/releases/download/main/windows-x64-release.zip -OutFile engine.zip
          Expand-Archive engine.zip -DestinationPath engine
          mv -Force engine/*  C:/hostedtoolcache/windows/flutter/stable-3.24.5-x64/bin/cache/artifacts/engine/windows-x64-release/

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: "1.75"
          targets: x86_64-pc-windows-msvc
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: "6f29f12e82a8293156836ad81cc9bf5af41fe836"
          doNotCache: false

      - name: Install vcpkg deps
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
        run: |
          $VCPKG_ROOT/vcpkg install --triplet x64-windows-static --x-install-root="$VCPKG_ROOT/installed"

      - name: Build RustDesk
        run: |
          python3 .\build.py --portable --hwcodec --flutter --vram --skip-portable-pack
          mv .\flutter\build\windows\x64\runner\Release .\rustdesk

      - name: Upload unsigned
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-unsigned-windows-x86_64
          path: rustdesk
